@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

actor User

box UI UI_COLOR_T1
participant ":CommandBox" as CB UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant "commandHistory:CommandHistory" as CH LOGIC_COLOR
end box

User -> CB : handleHistoryNavigation(KeyCode.UP)
activate CB

CB -> CH : getPrevious("")
activate CH

CH --> CB : "delete support@adafruit.com"
deactivate CH

CB -> CB : replaceCommandText("delete support@adafruit.com")
activate CB
CB --> CB
deactivate CB
CB --> User :
deactivate CB

@enduml
