@startuml
!include style.puml
skinparam ArrowFontStyle plain

box LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
end box

box MODEL_COLOR_T1
participant "m:ModelManager" as ModelManager MODEL_COLOR
participant "scoredPred:NameContainsKeywordsScoredPredicate" as sPred MODEL_COLOR
participant "associationPred:VendorEmailMatchesContactsPredicate" as aPred MODEL_COLOR
end box

note left of Logic
Parsing and command creation
is not shown
end note

activate Logic

create sPred
Logic -> sPred : NameContainsKeywordsScoredPredicate("adafruit")
activate sPred
sPred --> Logic : scoredPred
deactivate sPred

deactivate Logic

Logic -> ModelManager : updateFilteredPersonList(scoredPred)
activate Logic
activate ModelManager
deactivate ModelManager

Logic -> ModelManager : getFilteredPersonList()
activate ModelManager
ModelManager --> Logic : rankedFilteredPersons
deactivate ModelManager

create aPred
Logic -> aPred : VendorEmailMatchesContactsPredicate(rankedFilteredPersons)
activate aPred
aPred --> Logic : associationPred
deactivate aPred

Logic -> ModelManager : updateFilteredProductList(associationPred)
activate ModelManager
deactivate ModelManager

deactivate Logic

@enduml
