@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RestoreCommandParser" as RestoreCommandParser LOGIC_COLOR
participant "rc:RestoreCommand" as RestoreCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("restore support@adafruit.com")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("restore support@adafruit.com")
activate AddressBookParser

create RestoreCommandParser
AddressBookParser -> RestoreCommandParser
activate RestoreCommandParser
RestoreCommandParser --> AddressBookParser
deactivate RestoreCommandParser

AddressBookParser -> RestoreCommandParser : parse("support@adafruit.com")
activate RestoreCommandParser

create RestoreCommand
RestoreCommandParser -> RestoreCommand
activate RestoreCommand
RestoreCommand --> RestoreCommandParser
deactivate RestoreCommand

RestoreCommandParser --> AddressBookParser : rc
deactivate RestoreCommandParser
RestoreCommandParser -[hidden]-> AddressBookParser
destroy RestoreCommandParser

AddressBookParser --> LogicManager : rc
deactivate AddressBookParser

LogicManager -> RestoreCommand : execute(m)
activate RestoreCommand

RestoreCommand -> Model : getAddressBook().getPersonList()
activate Model
Model --> RestoreCommand : persons
deactivate Model

note right of RestoreCommand
  Filters for archived person
  matching the given email
end note

RestoreCommand -> Model : restorePerson(personToRestore)
activate Model
Model --> RestoreCommand
deactivate Model

RestoreCommand -> Model : commitVendorVault()
activate Model
Model --> RestoreCommand
deactivate Model

create CommandResult
RestoreCommand -> CommandResult
activate CommandResult
CommandResult --> RestoreCommand
deactivate CommandResult

RestoreCommand --> LogicManager : r
deactivate RestoreCommand

[<-- LogicManager
deactivate LogicManager
@enduml
